First attempt at updating to GL43C
slaytostay/region-locker pull request #20
Opened 2022-08-04 21:39 UTC by invalidCards

Needs more work; most functionality has been restored and switched to using GL43C project-wide but the chunks in the world are not being shaded yet.

@slaytostay Feel free to continue editing on this PR - you probably know a bit more about all the GPU stuff so I'll leave it to you :smile: (plus the dependency update was accepted anyway so it's in no rush)

2022-08-04 23:17 UTC, slaytostay requested changes
Looks great! I think only the geom shader is missing

2022-08-04 23:17 UTC, slaytostay commented on src/main/java/com/gpu/RegionGpuPlugin.java
> -			.add(GL4.GL_GEOMETRY_SHADER, "geom.glsl")
The gray region shader still uses the geometry shader, so this should also be ported to GL43C

2022-08-05 06:43 UTC, invalidCards commented
@slaytostay the geometry shader fails (syntax error) using GL43C - looks like you custom wrote it, so I'll leave the fixing of that to you x)

2022-08-05 07:19 UTC, slaytostay commented
The shader is originally from the GPU plugin, which they removed at some point, but heavily modified. I won't have a place to work on it for a bit, but it almost sounds like GL43C doesn't support geometry shaders. Which would be a shame, because that would mean we'd have to go back to the fuzzy gray border gradient between regions :/

2022-08-05 07:24 UTC, invalidCards commented
We might have to pull in and use the [geometry shader extension](https://javadoc.lwjgl.org/org/lwjgl/opengl/EXTGeometryShader4.html), as they did for the [anisotropic texture filtering extension](https://github.com/slaytostay/region-locker/pull/20/files#diff-2ad705726d6d072adb841117bd77de6293c332f1459f2cfb0f9332d504c46b37R109) in their update as well.

2022-08-05 07:30 UTC, slaytostay commented
Ah great, that might work. Is `org.lwjgl.opengl.EXTGeometryShader4` already importable? I might have some time to look at it tonight depending on what the weather does, but if so it might be pretty simple.

2022-08-05 07:34 UTC, invalidCards commented
Yep all of `org.lwjgl.opengl` is importable, including `EXTGeometryShader4` 🙂

2023-03-18 09:33 UTC, aHooder commented
Thanks for the effort, but I'm closing this in favour of #31

2023-03-18 09:33 UTC, closed without merging